# -*- coding: utf-8 -*-
"""Mask_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15yLvNFpB6bM5YTOwO4r_I2poFnCcFtlI
"""

import tensorflow as tf
import tensorflow_hub as hub
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
import numpy as np
import os

model_path = '/content/drive/MyDrive/Mask_Detection/model/mask_detection_model.h5'

IMG_SIZE = 224
model = tf.keras.models.load_model(model_path)

print("Model loaded successfully!")

# Class labels (update if necessary)
class_labels = {0: "With Mask", 1: "Without Mask"}

def predict_image(img_path):
    """
    Loads an image, preprocesses it, and makes a prediction.
    """
    # Load and preprocess the image
    img = tf.keras.preprocessing.image.load_img(img_path, target_size=(IMG_SIZE, IMG_SIZE))
    img_array = tf.keras.preprocessing.image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)  # Expand dimensions for batch input
    img_array = img_array / 255.0  # Normalize pixel values

    # Make prediction
    predictions = model.predict(img_array)
    predicted_class = np.argmax(predictions[0])
    confidence = predictions[0][predicted_class]

    # Get label from dictionary
    result = class_labels[predicted_class]
    print(f"Prediction: {result} (Confidence: {confidence:.2f})")
    return result, confidence


for file in os.listdir("/content/drive/MyDrive/Mask_Detection/test"):
  result, confidence = predict_image(file)
  plt.figure(figsize=(5, 5))
  plt.imshow(images[i])
  plt.title(f"Prediction: {result} (Confidence: {confidence:.2f})")
  print('==================================================')